version: "3"

services:
  dscheduler:
    image: peeriq/distributed:latest
    build: .
    ports:
     - "8786:8786"
     - "8787:8787"
     - "9786:9786"
    command: bash -c "source activate py3 && dask-scheduler --host dscheduler"
    networks:
      - distributed

  dworker:
    image: peeriq/distributed:latest
    build: .
    env_file: worker.env
    command: bash -c "source activate py3 && dask-worker dscheduler:8786"
    networks:
      - distributed

networks: 
  distributed:
    # driver: overlay
    ipam:
      config:
        - subnet: 50.0.0.0/24