version: "3"

services:
  dscheduler:
    image: ameier38/distributed:latest
    build: .
    ports:
     - "8786:8786"
    command: dask-scheduler --host dscheduler
    container_name: dscheduler

  dworker:
    image: ameier38/distributed:latest
    build: .
    env_file: worker.env
    command: dask-worker dscheduler:8786