version: "3"

services:
  dscheduler:
    image: ameier38/distributed:latest
    ports:
     - "8786:8786"
     - "8787:8787"
    command: start-dscheduler.sh
    container_name: dscheduler

  dworker:
    image: ameier38/distributed:latest
    command: start-dworker.sh