version: "3"

services:
  dscheduler:
    image: peeriq/distributed:latest
    build: .
    ports:
     - "8786:8786"
     - "8787:8787"
     - "9786:9786"
    command: start-scheduler.sh
    networks:
      distributed:
        aliases:
          - scheduler
    deploy:
      placement:
        constraints:
          - node.role == manager

  dworker:
    image: peeriq/distributed:latest
    build: .
    env_file: worker.env
    command: start-workers.sh
    networks:
      distributed:
        aliases:
          - worker

networks: 
  distributed:
    driver: overlay
    ipam:
      config:
        - subnet: 50.0.0.0/24